# Generated by Django 5.0.6 on 2024-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_alter_weatherforecast_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
