# Generated by Django 5.0.6 on 2024-06-19 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_alter_userquery_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userquery',
            constraint=models.UniqueConstraint(fields=('user', 'location', 'date', 'time'), name='unique_user_location_date_time'),
        ),
    ]
