# Generated by Django 5.0.6 on 2024-06-19 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_userquery_unique_user_location_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userquery',
            constraint=models.UniqueConstraint(condition=models.Q(('time__isnull', True)), fields=('user', 'location', 'date'), name='unique_user_location_date_no_time'),
        ),
        migrations.AddConstraint(
            model_name='weatherforecast',
            constraint=models.UniqueConstraint(fields=('location', 'date', 'time'), name='unique_location_date_time'),
        ),
        migrations.AddConstraint(
            model_name='weatherforecast',
            constraint=models.UniqueConstraint(condition=models.Q(('time__isnull', True)), fields=('location', 'date'), name='unique_location_date_no_time'),
        ),
    ]
