# Generated by Django 5.0.6 on 2024-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_weatherforecast_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='description',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Partly Cloudy', 'Partly Cloudy'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Snowy', 'Snowy'), ('Stormy', 'Stormy'), ('Foggy', 'Foggy'), ('Windy', 'Windy')], max_length=20),
        ),
    ]
